import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useState, useEffect, useRef } from "react";
import NasaInfo, { colors } from "../Components/NasaInfo";
import { colorState, selectedDateState } from "../Atoms/dateAtom";
import { useRecoilState } from "recoil";
import { shuffle } from "lodash";
import { ArrowCircleRightIcon } from "@heroicons/react/solid";

// CSS Modules, react-datepicker-cssmodules.css
// import 'react-datepicker/dist/react-datepicker-cssmodules.css';

export default function home() {
  const [vantaEffect, setVantaEffect] = useState(0);
  const [color, setColor] = useRecoilState(colorState);
  // animate the title & use gradient
  //use recoil for calendar background img
  // use rocket img on both sides of main img
  //try custom fonts for title

  return (
    <div className=" bg-violet-900  select-text ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" ">
        <NasaInfo />
      </main>
      <footer
        className={` h-[15vh] flex w-auto bg-gradient-to-t  ${color}`}
      ></footer>
    </div>
  );
}
