import Head from "next/head";
import NasaInfo from "../Components/NasaInfo";
import { colorState } from "../Atoms/dateAtom";
import { useRecoilState } from "recoil";

export default function home() {
  const [color] = useRecoilState(colorState);

  // use rocket img

  return (
    <div className=" bg-violet-900  select-text ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" ">
        <NasaInfo />
      </main>
      <footer
        className={` h-[15vh] flex w-auto bg-gradient-to-t  ${color}`}
      ></footer>
    </div>
  );
}
