import Head from "next/head";
import NasaInfo from "../Components/NasaInfo";
import { useRecoilState } from "recoil";
import { colorState } from "../atoms/dateAtom";

export default function Home() {
  // use rocket img
  const [color, setColor] = useRecoilState(colorState);
  return (
    <div className=" bg-violet-900  select-text ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" ">
        <NasaInfo />
      </main>
      <footer
        className={`flex min-h-[15vh] flex-col  w-[100%] justify-center bg-gradient-to-t ${color} `}
      ></footer>
    </div>
  );
}
